version: "3.5"
services:
  sequencer:
    build:
      context: sequencer
      args:
        UPSTREAM_VERSION: 2.0.2
        DATA_DIRECTORY: /data
    volumes:
      - sequencer-data:/data
    environment:
      COINBASE: ""
      VALIDATOR_PRIVATE_KEYS: ""
      BLOB_SINK_URL: ""
      SYNC_SNAPSHOTS_URL: ""
      LOG_LEVEL: "info"
    restart: unless-stopped
volumes:
  sequencer-data: {}
